### ISSUE TITLE
новая строка и ссылки

### ISSUE THREAD

**Issue by valsha** [EvgeniiR/ws-chat#1]
Добрый вечер. Интересный проект и реализация.
Пара моментов
1. В строке где писать сообщения, если писать часто то переходит на новую строку в окне, а не с верху пишет в поле.
2. Если написать в чате к примеру ссылку https://google,com то ее обработает просто как текст, ссылка в чате не активна.
Спасибо.

**Comment by EvgeniiR** [comment]
Добрый день!

Всё исправлено, ссылки подсвечиваются.

Спасибо за обратную связь!

**Comment by valsha** [comment]
сломались ссылки в чате :)

**Comment by EvgeniiR** [comment]
Упс.. Зыбыл добавить парсинг ссылок на vue. Спасибо, добавлю )

пн, 12 нояб. 2018 г. в 11:01, valsha.github.io <notifications@github.com>:
